[package]
name = "nitro"
version = "0.1.0"
edition = "2021"

[dependencies]
llvm-sys = { version = "160", features = ["strict-versioning"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
toml = "0.8"
